variable "aws_region" {
  type    = string
  default = "sa-east-1"

  validation {
    condition     = var.aws_region == "sa-east-1"
    error_message = "Conora runs only in sa-east-1 (Sao Paulo)."
  }
}

variable "expected_account_id" {
  type        = string
  default     = "371664303999"
  description = "Account gate: Terraform refuses to run against any other AWS account."
}

variable "project" {
  type    = string
  default = "conora"
}

variable "environment" {
  type        = string
  default     = "dev"
  description = "Resource-name prefix of the only AWS stack. That stack is production (conora.com.br). Do not rename it: Terraform would replace RDS, EC2 and secrets."
}

variable "domain" {
  type    = string
  default = "conora.com.br"
}

variable "api_subdomain" {
  type    = string
  default = "api"
}

variable "db_name" {
  type    = string
  default = "conora"
}

variable "db_username" {
  type    = string
  default = "conora_admin"
}

variable "ec2_instance_type" {
  type    = string
  default = "t4g.small"
}

variable "rds_instance_class" {
  type    = string
  default = "db.t4g.micro"
}

variable "allowed_ssh_cidr" {
  type        = string
  default     = ""
  description = "Optional SSH CIDR. Empty = SSH closed (use SSM Session Manager)."
}

variable "google_client_id" {
  type    = string
  default = "943760588490-ugpetcnbu8s0sac6rkss5r8ingn6g2pl.apps.googleusercontent.com"
}

variable "ses_from" {
  type    = string
  default = "noreply@conora.com.br"
}

variable "budget_limit_usd" {
  type    = number
  default = 90
}

variable "alert_email" {
  type    = string
  default = "flavio@redfivesistemas.com.br"
}

variable "github_actions_repo_api" {
  type    = string
  default = "flaviobarbosac/conora"
}

variable "github_actions_repo_front" {
  type    = string
  default = "flaviobarbosac/conora-front"
}

# --- Secrets Manager inputs (set in terraform.tfvars; never commit) ---

variable "jwt_key" {
  type        = string
  default     = ""
  sensitive   = true
  description = "JWT HS256 key (min. 32 chars). Empty = generated by Terraform."
}

variable "gemini_api_key" {
  type      = string
  default   = ""
  sensitive = true
}

variable "gemini_model" {
  type    = string
  default = ""
}

variable "whatsapp_access_token" {
  description = "Meta WhatsApp Cloud API permanent/system user token for outbound replies"
  type        = string
  default     = ""
  sensitive   = true
}

variable "whatsapp_phone_number_id" {
  description = "Meta WhatsApp Cloud API phone number id used to send messages"
  type        = string
  default     = ""
}

variable "whatsapp_verify_token" {
  type      = string
  default   = ""
  sensitive = true
}

variable "whatsapp_app_secret" {
  type      = string
  default   = ""
  sensitive = true
}
